---
services:
  task-tracker:
    build:
      context: ../../../../
      dockerfile: app/base_image/Dockerfile
    image: base-python:3.12.5
    ports:
      - "${TASK_TRACKER_PORT}:${TASK_TRACKER_INTERNAL_PORT}"
    volumes:
      - ../:/app
      - ../../../../common:/app/common
    env_file:
      - ../../../../.env
    environment:
      PROJECT_NAME: ${PROJECT_NAME}
      VERSION: ${VERSION}
      API_V1_STR: ${API_V1_STR}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    command: ["python", "-m", "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "${TASK_TRACKER_INTERNAL_PORT}", "--reload"]
    healthcheck:
      test: ["CMD-SHELL", "curl http://localhost:${TASK_TRACKER_INTERNAL_PORT}/healthcheck || exit 1"]
      interval: 5s
      retries: 10
      start_period: 10s
      timeout: 10s
