---
services:
  task-tracker:
    build:
      context: ../../../../
      dockerfile: app/base_image/Dockerfile
    image: base-python:3.12.5
    ports:
      - "${TASK_TRACKER_PORT}:${TASK_TRACKER_INTERNAL_PORT}"
    volumes:
      - ../:/app
      - ../../../../common:/app/common
    env_file:
      - ../../../../.env
    environment:
      APP_NAME: task_tracker
      PORT: ${TASK_TRACKER_INTERNAL_PORT}
    command: ["python", "-m", "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "${TASK_TRACKER_INTERNAL_PORT}", "--reload"]
    healthcheck:
      test: ["CMD-SHELL", "curl http://localhost:${TASK_TRACKER_INTERNAL_PORT}/healthcheck || exit 1"]
      interval: 5s
      retries: 10
      start_period: 10s
      timeout: 10s