---
services:
  db-migrator:
    build:
      context: ../../../..
      dockerfile: app/microservices/db_migrator/Dockerfile
    env_file:
      - ../../../../.env
    environment:
      CONNECTION_APP_NAME: db_migrator
    depends_on:
      postgres:
        condition: service_healthy
